# permissions for end users to view previewenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pr-env
    app.kubernetes.io/managed-by: kustomize
  name: previewenvironment-viewer-role
rules:
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments/status
  verbs:
  - get
