# permissions for end users to edit previewenvironmentinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pr-env
    app.kubernetes.io/managed-by: kustomize
  name: previewenvironmentinstance-editor-role
rules:
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances/status
  verbs:
  - get
