---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances/finalizers
  verbs:
  - update
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances/status
  verbs:
  - get
  - patch
  - update
