---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances/finalizers
  verbs:
  - update
- apiGroups:
  - coflnet.coflnet.com
  resources:
  - previewenvironmentinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
