//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSettings) DeepCopyInto(out *ApplicationSettings) {
	*out = *in
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = new([]EnvironmentVariable)
		if **in != nil {
			in, out := *in, *out
			*out = make([]EnvironmentVariable, len(*in))
			copy(*out, *in)
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSettings.
func (in *ApplicationSettings) DeepCopy() *ApplicationSettings {
	if in == nil {
		return nil
	}
	out := new(ApplicationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildSettings) DeepCopyInto(out *BuildSettings) {
	*out = *in
	if in.BranchWildcard != nil {
		in, out := &in.BranchWildcard, &out.BranchWildcard
		*out = new(string)
		**out = **in
	}
	if in.DockerfilePath != nil {
		in, out := &in.DockerfilePath, &out.DockerfilePath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildSettings.
func (in *BuildSettings) DeepCopy() *BuildSettings {
	if in == nil {
		return nil
	}
	out := new(BuildSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltVersion) DeepCopyInto(out *BuiltVersion) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltVersion.
func (in *BuiltVersion) DeepCopy() *BuiltVersion {
	if in == nil {
		return nil
	}
	out := new(BuiltVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistry) DeepCopyInto(out *ContainerRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistry.
func (in *ContainerRegistry) DeepCopy() *ContainerRegistry {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentVariable) DeepCopyInto(out *EnvironmentVariable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentVariable.
func (in *EnvironmentVariable) DeepCopy() *EnvironmentVariable {
	if in == nil {
		return nil
	}
	out := new(EnvironmentVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSettings) DeepCopyInto(out *GitSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSettings.
func (in *GitSettings) DeepCopy() *GitSettings {
	if in == nil {
		return nil
	}
	out := new(GitSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceGitSettings) DeepCopyInto(out *InstanceGitSettings) {
	*out = *in
	if in.Branch != nil {
		in, out := &in.Branch, &out.Branch
		*out = new(string)
		**out = **in
	}
	if in.PullRequestNumber != nil {
		in, out := &in.PullRequestNumber, &out.PullRequestNumber
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceGitSettings.
func (in *InstanceGitSettings) DeepCopy() *InstanceGitSettings {
	if in == nil {
		return nil
	}
	out := new(InstanceGitSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironment) DeepCopyInto(out *PreviewEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironment.
func (in *PreviewEnvironment) DeepCopy() *PreviewEnvironment {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreviewEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentInstance) DeepCopyInto(out *PreviewEnvironmentInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentInstance.
func (in *PreviewEnvironmentInstance) DeepCopy() *PreviewEnvironmentInstance {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreviewEnvironmentInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentInstanceList) DeepCopyInto(out *PreviewEnvironmentInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PreviewEnvironmentInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentInstanceList.
func (in *PreviewEnvironmentInstanceList) DeepCopy() *PreviewEnvironmentInstanceList {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreviewEnvironmentInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentInstanceSpec) DeepCopyInto(out *PreviewEnvironmentInstanceSpec) {
	*out = *in
	in.InstanceGitSettings.DeepCopyInto(&out.InstanceGitSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentInstanceSpec.
func (in *PreviewEnvironmentInstanceSpec) DeepCopy() *PreviewEnvironmentInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentInstanceStatus) DeepCopyInto(out *PreviewEnvironmentInstanceStatus) {
	*out = *in
	if in.BuiltVersions != nil {
		in, out := &in.BuiltVersions, &out.BuiltVersions
		*out = make([]BuiltVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentInstanceStatus.
func (in *PreviewEnvironmentInstanceStatus) DeepCopy() *PreviewEnvironmentInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentList) DeepCopyInto(out *PreviewEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PreviewEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentList.
func (in *PreviewEnvironmentList) DeepCopy() *PreviewEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreviewEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentSpec) DeepCopyInto(out *PreviewEnvironmentSpec) {
	*out = *in
	out.GitSettings = in.GitSettings
	if in.ContainerRegistry != nil {
		in, out := &in.ContainerRegistry, &out.ContainerRegistry
		*out = new(ContainerRegistry)
		**out = **in
	}
	in.ApplicationSettings.DeepCopyInto(&out.ApplicationSettings)
	in.BuildSettings.DeepCopyInto(&out.BuildSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentSpec.
func (in *PreviewEnvironmentSpec) DeepCopy() *PreviewEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviewEnvironmentStatus) DeepCopyInto(out *PreviewEnvironmentStatus) {
	*out = *in
	if in.PullRequestsDetected != nil {
		in, out := &in.PullRequestsDetected, &out.PullRequestsDetected
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviewEnvironmentStatus.
func (in *PreviewEnvironmentStatus) DeepCopy() *PreviewEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(PreviewEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}
